### ISSUE TITLE
How to preserve the order of transduced items?

### ISSUE THREAD

**Issue by moroshko** [universal-automata/liblevenshtein-coffeescript#1]
First of all thanks for sharing your work with the world!

I'm using the Javascript version, and I have a question regarding the `.dictionary(locations, false)` bit here:

(code below is in es6)

``` js
import levenshtein from 'liblevenshtein';
const transducer = new levenshtein
  .Builder()
  .dictionary(locations, false) // What does false mean?
  .algorithm('transposition')
  .include_distance(false)
  .build();
...
const matches = transducer.transduce(query, 1);
```

When should I pass `true` and when should I pass `false` to `.dictionary()`?

How could I guarantee that `matches` are in the same order as `locations`?

For example, if `query = 'elbourne'`, and `locations` is:

``` js
['melbourne', 'sydney', 'london', 'selbourne', 'adelaide', 'delbourne'];
```

I want to make sure that `matches` is:

``` js
['melbourne', 'selbourne', 'delbourne']
```

(the order of locations is preserved in `matches`)

**Comment by dylon** [comment]
The API is described in the wiki.  See the breakdown of the builder attributes:

https://github.com/universal-automata/liblevenshtein/wiki/usage.coffeescript

The second parameter specifies whether the list of terms is already sorted lexicographically.  If you pass-in false then the list will be sorted by the library.  If you have a very large list then you probably want to sort it before loading it into your application, and let the library know it's been sorted by passing-in true as the second parameter.

At the moment, the JS library only supports ordering candidates lexicographically or in whichever order it identifies them (non-deterministic).  You would have to extend the classes to override the sorting logic.  I'm not happy with the current design, and have been working on a new version, but I've been busy with other projects so I haven't had time to finish the implementation.

**Comment by dylon** [comment]
You could apply the ordering once you've extracted the spelling candidates.  That would be the easiest solution.

**Comment by moroshko** [comment]
@dylon Thanks for your response!
