### ISSUE TITLE
Construction of Dawg Stomps on Prefixes

### ISSUE THREAD

**Issue by suprafly** [universal-automata/liblevenshtein-coffeescript#3]
Please see that the following test will fail:

```
// https://github.com/universal-automata/liblevenshtein-coffeescript/blob/master/src/collection/dawg.coffee
// Test 
var dictionary = [ "about", "after", "all", "and", "about and", "afterall" ];
var dawg = new Dawg(dictionary);
console.log(dawg.accepts("after"));
```

This fails because the construction of the Dawg is stomping on the nodes of prefixes, thus causing the 'is_final' attribute to be set to false.

The important thing to realize is that [the original article which this algorithm is patterned on ](http://stevehanov.ca/blog/index.php?id=115) requires that a list be sorted before it is added. The reason for this is because that is the only way to be certain that the previous word has the possibility of being a prefix to the next word being inserted.

This won't work because there is no guarantee that, given an unsorted list, the previous word will share a prefix with the current word. (That guarantee is ensured by having a presorted list):

```
# Find longest common prefix between word and previous word
i = 0; previous_word = @previous_word
upper_bound =
  if word.length < previous_word.length
    word.length
  else
    previous_word.length

i += 1 while i < upper_bound and word[i] is previous_word[i]
```

As far as I can tell, the only way to construct a Dawg from an unsorted list would be to construct the entire trie first, then compress it. The reason that the referenced algorithm is so efficient is because pre-sorting guarantees that a trie branch can be minimized directly after construction.

**Comment by dylon** [comment]
This is documented in the wiki; I'm looking into supporting online dictionaries.  The builder will sort your terms if you'd like:

https://github.com/universal-automata/liblevenshtein/wiki/usage.coffeescript

Regards,
Dylon
